/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mstruzek_jni_JNISolverGate */

#ifndef _Included_com_mstruzek_jni_JNISolverGate
#define _Included_com_mstruzek_jni_JNISolverGate
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mstruzek_jni_JNISolverGate_JNI_SUCCESS
#define com_mstruzek_jni_JNISolverGate_JNI_SUCCESS 0L
#undef com_mstruzek_jni_JNISolverGate_JNI_ERROR
#define com_mstruzek_jni_JNISolverGate_JNI_ERROR 1L
/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mstruzek_jni_JNISolverGate_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    setBooleanProperty
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_setBooleanProperty
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    setLongProperty
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_setLongProperty
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    setDoubleProperty
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_setDoubleProperty
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    initDriver
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_initDriver
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    initComputationContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_initComputationContext
  (JNIEnv *, jclass);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    getCommitTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mstruzek_jni_JNISolverGate_getCommitTime
  (JNIEnv *, jclass);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    registerPointType
 * Signature: (IDD)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_registerPointType
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    registerGeometricType
 * Signature: (IIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_registerGeometricType
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    registerParameterType
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_registerParameterType
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    registerConstraintType
 * Signature: (IIIIIIIDD)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_registerConstraintType
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jdouble, jdouble);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    initComputation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_initComputation
  (JNIEnv *, jclass);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    solveSystem
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_solveSystem
  (JNIEnv *, jclass);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    getSolverStatistics
 * Signature: ()Lcom/mstruzek/msketch/solver/SolverStat;
 */
JNIEXPORT jobject JNICALL Java_com_mstruzek_jni_JNISolverGate_getSolverStatistics
  (JNIEnv *, jclass);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    fetchStateVector
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_mstruzek_jni_JNISolverGate_fetchStateVector
  (JNIEnv *, jclass);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    updateStateVector
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_updateStateVector
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    updateConstraintState
 * Signature: ([I[D[DI)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_updateConstraintState
  (JNIEnv *, jclass, jintArray, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    updateParametersValues
 * Signature: ([I[DI)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_updateParametersValues
  (JNIEnv *, jclass, jintArray, jdoubleArray, jint);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    getPointPXCoordinate
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_mstruzek_jni_JNISolverGate_getPointPXCoordinate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    getPointPYCoordinate
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_mstruzek_jni_JNISolverGate_getPointPYCoordinate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    destroyComputation
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_destroyComputation
  (JNIEnv *, jclass);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    destroyComputationContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_destroyComputationContext
  (JNIEnv *, jclass);

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    closeDriver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_closeDriver
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
