/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mstruzek_jni_JNISolverGate */

#ifndef _Included_com_mstruzek_jni_JNISolverGate
#define _Included_com_mstruzek_jni_JNISolverGate
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mstruzek_jni_JNISolverGate_ERROR_SUCCESS
#define com_mstruzek_jni_JNISolverGate_ERROR_SUCCESS 0L
#undef com_mstruzek_jni_JNISolverGate_ERROR_FAILURE
#define com_mstruzek_jni_JNISolverGate_ERROR_FAILURE 1L

#define ERROR_SUCCESS com_mstruzek_jni_JNISolverGate_ERROR_SUCCESS
#define ERROR_FAILURE com_mstruzek_jni_JNISolverGate_ERROR_FAILURE

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    initDriver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_initDriver
  (JNIEnv *, jclass)
{
    return ERROR_SUCCESS;
}

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mstruzek_jni_JNISolverGate_getLastError
  (JNIEnv *, jclass)
{
    return NULL;
}


/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    closeDriver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_closeDriver
  (JNIEnv *, jclass)
{
    return ERROR_SUCCESS;
}

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    resetDatabase
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_resetComputationData
  (JNIEnv *, jclass)
{
    return ERROR_SUCCESS;
}


/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    resetComputationContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_resetComputationContext
  (JNIEnv *, jclass)
{
    return ERROR_SUCCESS;
}


/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    initComputationContext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_initComputationContext
  (JNIEnv *, jclass)
{
    return ERROR_SUCCESS;
}


/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    solveSystem
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_solveSystem
  (JNIEnv *, jclass)
{
    return ERROR_SUCCESS;
}


/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    registerPointType
 * Signature: (IDD)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_registerPointType
  (JNIEnv *, jclass, jint, jdouble, jdouble)
{
    return ERROR_SUCCESS;
}


/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    registerGeometricType
 * Signature: (IIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_registerGeometricType
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint)
{
    return ERROR_SUCCESS;
}


/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    registerParameterType
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_registerParameterType
  (JNIEnv *, jclass, jint, jdouble)
{
    return ERROR_SUCCESS;
}


/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    registerConstraintType
 * Signature: (IIIIIIDD)I
 */
JNIEXPORT jint JNICALL Java_com_mstruzek_jni_JNISolverGate_registerConstraintType
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jdouble, jdouble)
{
    return ERROR_SUCCESS;
}


/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    getPointPXCoordinate
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_mstruzek_jni_JNISolverGate_getPointPXCoordinate
  (JNIEnv *, jclass, jint)
{
    return (jdouble)0.0;
}


/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    getPointPYCoordinate
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_mstruzek_jni_JNISolverGate_getPointPYCoordinate
  (JNIEnv *, jclass, jint)
{
    return (jdouble)0.0;
}

/*
 * Class:     com_mstruzek_jni_JNISolverGate
 * Method:    getPointCoordinateVector
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_mstruzek_jni_JNISolverGate_getPointCoordinateVector
  (JNIEnv *, jclass)
  {
      return (jdoubleArray)NULL;
  }


#ifdef __cplusplus
}
#endif
#endif
